version: 2.1

jobs:
  build:
    circleci_ip_ranges: true # opts the job into the IP ranges feature
    docker:
      - image: cimg/python
    steps:
      - run: python -m http.server 80
workflows:
  build-workflow:
    jobs:
      - build
